documentation/categories/themes.md

See https://www.home-assistant.io/integrations/frontend/#themes

fix config example

---

documentation/installation/manual.md

Previously the instructions were very long and it made it sound complicated. There were also a lot of distracting comments that I deleted.

update the installation instructions

---

documentation/categories/themes.md

It should be "theme: true" and not "themes"

Configuration Correction

---

documentation/publish/start.md

I did not bother with updating the screenshot though. If you would like me to, let me know.

Compact Custom Header has been replaced by Compact Header

---

documentation/installation/prerequisites.md

Small typo correction

---

documentation/publish/plugin.md

Discovered a small typo while browsing the docs 😊

Removed typo in plugin.md

---

documentation/publish/integration.md

Remove minimum homeassistant release

---

documentation/installation/prerequisites.md

`In computing, bandwidth is the maximum rate of data transfer across a given path`.
Since the problem is the amount of data, rather than how fast the data comes down, I'd suggest using the more explicit "data cap" (`A data cap, often erroneously referred to as a bandwidth cap, is an artificial restriction imposed on the transfer of data over a network.`)

Better connection requirement explanation

---

documentation/faq/what.md

Fixed a type in FAQ with missing 'e'…

fixed a typo

---

documentation/publish/integration.md
documentation/publish/start.md

I have tried to clarify the documentation a bit, especially for newbies like me who is trying to make a custom integration conform to HACS standards for the first time.
Let me know if anything is unclear or if something needs to be modified further.

Iot class clarification

---

documentation/basic/automation.md
documentation/basic/data.md
documentation/categories/integrations.md
documentation/developer/documentation.md
documentation/developer/frontend.md
documentation/faq/initial_startup.md
documentation/faq/status_not_loaded.md
documentation/installation/prerequisites.md
documentation/installation/remove.md
documentation/issues.md
documentation/publish/include.md
documentation/publish/start.md

I've fixed a few of spelling and grammar errors, as well as one or two formatting issues.

Fixed spelling and grammar issues

---

documentation/publish/start.md

Add warning

---

documentation/developer/frontend.md

Frontend setup instructions are outdated so this PR updates them to the current state of the project

Update frontend setup

---

documentation/configuration/pat.md

Add instructions about placing the token in the config file! These instructions are available on other pages but it makes sense to include them in the step-by-step guide?

Update pat.md to add configuration instructions

---

documentation/faq/custom_repositories.md

Came across this issue and then found a ticket about it with a request for this to be included in the docs

Documenting the hidden behaviour

---

src/pages/index.js
src/pages/styles.module.css

I have made a couple of fixes to the index page
- Buttons now have spacing between them
- Hero element now scales so on desktops so the features element touches the bottom of the screen
Before:
After

Fixes to index page

---

documentation/publish/include.md

Add check requirements section

---

documentation/setup/prerequisites.md

Editing a typo and correcting some grammar on the Prerequisites page

Editing the Prerequisites page

---

documentation/setup/download.mdx

Fixes https://github.com/hacs/integration/issues/2555

Add additional paste methods in Troubleshooting

---

documentation/categories/plugins.md

I renamed Lovelace to UI in plugins

Rename Lovelace to UI

---

source/docs/use/download/download.md

Download HACS: Update
- Update OS and Supervised steps to use the new HACS installation repository and add-on

Download HACS: Update OS steps to include add-on

---

source/docs/use/type/python_script.md

Python Script: rephrase

---

source/docs/faq/github_account.md

FAQ GitHub account: rephrase

---

source/docs/use/type/dashboard.md

- add a bit more structure to nerd mode section
- move alias section below intro section

Dashboard rephrase

---

source/docs/use/repositories/dashboard.md

- steps to update repo meta data using the Update information button
- explain difference to downloading a repo
- add info that when downloading, you can select a specific version
- fix list indents

Update repository meta data

---

source/docs/use/data.md

The last couple of releases have overhauled how backups work

Update backup documentation links

---

source/docs/publish/include.md

For https://github.com/hacs/default/pull/3405

Add documentation for the new release check

---

source/docs/publish/start.md

Corrected link to the `AwesomeVersion` demo

Corrected link to AwesomeVersion in start.md
